// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rphveagdqxczpnozcmwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwaHZlYWdkcXhjenBub3pjbXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NjU3ODQsImV4cCI6MjA4NjA0MTc4NH0.FAtxuoBzn8EUtcLe38sRB1_dF6n_Ncu9NI99dVWDBLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});